### ISSUE TITLE
Gamora's Switchblade

### ISSUE THREAD

**Issue by 24shreya** [GDSC-Techno/Save-the-world#1]
In the [`Gamora_switchblade.cpp`](https://github.com/GDSC-Techno/Save-the-world/blob/main/MARVEL/Gamora_switchblade.cpp) file, Gamora's switchblade looks like this :

![fest21_11-copy](https://user-images.githubusercontent.com/79649501/136670899-2f625190-464a-484d-949f-e56a7a4ecb63.PNG)

Modify the code and complete her blade to look like so : 

![fest21_12-copy](https://user-images.githubusercontent.com/79649501/136670912-8bb625e3-dd45-4cfe-8044-e6a7879c2d6e.PNG)

##### Last but not the least, Gamora's actual switchblade 🤩 

![switchblade_gamora](https://user-images.githubusercontent.com/79649501/136670721-30e2d8a4-42cc-4fb1-a498-c0069d7fb3b4.jpg)

**Comment by vaibhavraj-nath-chauhan** [comment]
Can I work on this issue? I am a beginner and learning how to contribute to open-source

**Comment by jkugsiya** [comment]
> Can I work on this issue? I am a beginner and learning how to contribute to open-source

Great @Vaibhavraj-nath-chauhan! Assigning this to you.

**Comment by vaibhavraj-nath-chauhan** [comment]
Is my old commit is acceptable or I have to make new commit

**Comment by jkugsiya** [comment]
> Is my old commit is acceptable or I have to make new commit

Yes that is acceptable and your PR got merged don't worry.

**Comment by vaibhavraj-nath-chauhan** [comment]
Thank you @jkugsiya for your help and support
